### ISSUE TITLE
User can search for different product types

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/Se-Fauxra#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for different product types

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can search for different product types through a search bar. Once a specific product is entered, users will be able to see a list of products that match.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile: 
<img width="686" alt="Screen Shot 2022-09-26 at 9 07 17 AM" src="https://user-images.githubusercontent.com/60860374/192326407-a13baa83-001b-49d4-bcaa-59d09ba58822.png">
Desktop:
![Screen Shot 2022-09-26 at 9 08 19 AM](https://user-images.githubusercontent.com/60860374/192326605-f5b2acaf-c700-437a-aed1-dbab9c4b9b21.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create form for search bar
- [x] Request the data for all Maybelline products from the makeup API
- [x] Create dummy data to display.
- [x] Target the name, price, rating, and api_featured_image properties of each product to display on the page
- [x] Style the page so the products match the wireframe
- [x] Make sure all products are hidden prior to any searches
- [x] Listen for keydown events on search bar to update the page with matching 'products_type' when the 'enter' button is pressed
- [x] Ensure that the feature looks nice on both mobile-sized and desktop-sized screens
  - [x] Three products show per row on desktop
  - [x] One product shows per row on mobile

 Clean Up
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all commented out code and console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Test the app some more in a private browsing tab.
