### ISSUE TITLE
User can view information on a product

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/Se-Fauxra#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view information on a different product

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user clicks on a product of interest, the user will be brought to a page with more detailed information regarding the product.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![Screen Shot 2022-09-26 at 9 38 41 AM](https://user-images.githubusercontent.com/60860374/192333029-20608aa3-20dc-4bff-83bd-510cd95bd028.png)

Desktop:
![Screen Shot 2022-09-26 at 9 38 05 AM](https://user-images.githubusercontent.com/60860374/192332900-65c8edb7-e841-425d-ac98-885a108fb01c.png)
![Screen Shot 2022-09-26 at 9 38 18 AM](https://user-images.githubusercontent.com/60860374/192332942-aa2df1e3-7c9d-4826-94ca-8227619cb801.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When user hovers over a product, the border should thicken
- [x] Create a data model that includes a view property
- [x] Create and style dummy data for a product to reflect the wireframes
  - [x] Mobile: Make sure the image is underneath the brand and product name
    - [x] Mobile view includes 'About The Product' header 
  - [x] Desktop: Make sure the image is to the left of the product name, price, and rating
- [x] Update loadData function to assign each product an id #
- [x] Define a function that takes each product and creates a DOM tree that matches the dummy data
  - [x] Make sure each product has a product id #
  - [x] Hide all products
- [x] Listen for click event on the ul element:
  - [x] When user clicks on item, they are taken to the data-view: products page featuring information about that specific product -- all other products are hidden
  - [x] The page should display the brand, name, price, rating, description, and image
- [x] Make any further styling changes so the page matches the wireframes for mobile and desktop

Clean Up
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
