### ISSUE TITLE
User can add products to a wishlist

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/Se-Fauxra#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add products to a wishlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can add products to a wishlist by clicking on the heart icon next to any product. Once the heart is selected, the heart icon fills in and the item is added to a wishlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![Screen Shot 2022-09-26 at 9 41 58 AM](https://user-images.githubusercontent.com/60860374/192333667-943d603a-0770-4eef-aa66-33887c7aae56.png)

Desktop:
![Screen Shot 2022-09-26 at 9 41 17 AM](https://user-images.githubusercontent.com/60860374/192333532-a44e11be-5cb3-4f9c-9f11-f8ccd3a14ea6.png)
![Screen Shot 2022-09-26 at 9 41 30 AM](https://user-images.githubusercontent.com/60860374/192333581-721b04a6-c014-4a1b-8287-4a049ba18a23.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update renderData function to include a heart icon for each list item 
  - [x] Heart icon for each product item 
  - [x] Heart icon for each product information on mobile 
  - [x] Heart icon for each product information on desktop
- [x] Listen for clicks on the product list and product information, if the heart icon is clicked...
  - [x] The heart becomes filled in
  - [x] If the heart is filled in on the product info page, the matching heart from the product list should also be filled in and vice versa.
  - [x] The matching product data is added to the wishlist property of the data model
  - [x] Ensure that the wishlist item is given a data-wishlist-id #
  - [x] Verify that each new wishlist item receives an incrementing wishlist-id
  - [x] Verify that wishlist items are saved to local storage data model 
 
Clean Up
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
