### ISSUE TITLE
User can view products on their wishlist

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/Se-Fauxra#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view products on their wishlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on the wishlist tab on the navigation bar, they are taken to a page that displays all items on their wishlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![Screen Shot 2022-09-26 at 9 43 19 AM](https://user-images.githubusercontent.com/60860374/192333912-d0aa40f8-cde3-4a90-a180-509055def00f.png)

Desktop:
![Screen Shot 2022-09-26 at 9 43 47 AM](https://user-images.githubusercontent.com/60860374/192334007-2936701c-0d76-4459-ac1b-67d1a97c304c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create wishlist view:
  - [x] If user has no products on the wishlist, it should read "There are no products currently on your wishlist"
- [x] Add anchor tags to the nav bar for user to access search feature and their wishlist
  - [x] Style anchor tags to reflect wireframe
  - [x] When user clicks on search, they should be taken to the search page
  - [x] When user clicks on wishlist, they should be taken to their wishlist page
- [x] Use a loop to create a DOM tree for each wishlist item in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Update the function so that when the user adds a product to the wishlist, a DOM tree of the product should be generated and appended to the wishlist
- [x] Ensure that refreshing the page shows the same view as before refreshing
- [x] Style wishlist to reflect wireframes
  - [x] Desktop view should have 2 items per row
  - [x] Mobile view should have 1 item per row

Clean Up
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens
