### ISSUE TITLE
User can remove products on their wishlist 

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/Se-Fauxra#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove products on their wishlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users click on the shaded heart, it removes the product from their wishlist. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![Screen Shot 2022-09-26 at 9 45 13 AM](https://user-images.githubusercontent.com/60860374/192334224-50ba7ff7-51e1-41cf-bfcf-84e32c5b01f4.png)

Desktop:
![Screen Shot 2022-09-26 at 9 45 27 AM](https://user-images.githubusercontent.com/60860374/192334284-0d22ac9e-dbe5-4fad-a99f-ce935b48b0e7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Use the heart icon as a click target for deleting a wishlist item
- [x] When the user clicks the heart target on the wishlist view:
  - [x] Remove the item from the wishlist in the data model
  - [x] Remove the item's DOM tree from the page

Additional tweaks
- [x] Make the hearts of the products on the wishlist stay shaded in on the individual products and product descriptions when on refresh

Clean Up
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
